modLoader="javafml"
loaderVersion="40.3.3"
license="MIT"

[[mods]]
modId="magicraft"
version="0.1.0"
displayName="Magi(c)raft"
description="Magi(c)raft, Many Magic"
authors="elecbug"

[[dependencies.mymodid]]
modId="forge"
mandatory=true
versionRange="40.3.3"
ordering="NONE"
side="BOTH"
