modLoader="javafml"
loaderVersion="40.3.3"
license="MIT"

[[mods]]
modId="plantia"
version="0.1.1"
displayName="Plantia"
description="Plantia"
authors="elecbug"

[[dependencies.plantia]]
modId="forge"
mandatory=true
versionRange="40.3.3"
ordering="NONE"
side="BOTH"
